### build_subway_graph

In [2]:
import pandas as pd

stations = pd.read_csv("../raw/stations.csv")
complexes = pd.read_csv("../raw/complexes.csv")

print("=== Stations ===")
display(stations.head())
print(stations.columns.tolist())

print("\n=== Complexes ===")
display(complexes.head())
print(complexes.columns.tolist())

=== Stations ===

,GTFS Stop ID,Station ID,Complex ID,Division,Line,Stop Name,Borough,CBD,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude,North Direction Label,South Direction Label,ADA,ADA Northbound,ADA Southbound,ADA Notes,Georeference
0,R01,1,1,BMT,Astoria,Astoria-Ditmars Blvd,Q,False,N W,Elevated,40.775036,-73.912034,Last Stop,Manhattan,0,0,0,NaN,POINT (-73.912034 40.775036)
1,R03,2,2,BMT,Astoria,Astoria Blvd,Q,False,N W,Elevated,40.770258,-73.917843,Astoria,Manhattan,1,1,1,NaN,POINT (-73.917843 40.770258)
2,R04,3,3,BMT,Astoria,30 Av,Q,False,N W,Elevated,40.766779,-73.921479,Astoria,Manhattan,0,0,0,NaN,POINT (-73.921479 40.766779)
3,R05,4,4,BMT,Astoria,Broadway,Q,False,N W,Elevated,40.761820,-73.925508,Astoria,Manhattan,0,0,0,NaN,POINT (-73.925508 40.76182)
4,R06,5,5,BMT,Astoria,36 Av,Q,False,N W,Elevated,40.756804,-73.929575,Astoria,Manhattan,0,0,0,NaN,POINT (-73.929575 40.756804)

['GTFS Stop ID', 'Station ID', 'Complex ID', 'Division', 'Line', 'Stop Name', 'Borough', 'CBD', 'Daytime Routes', 'Structure', 'GTFS Latitude', 'GTFS Longitude', 'North Direction Label', 'South Direction Label', 'ADA', 'ADA Northbound', 'ADA Southbound', 'ADA Notes', 'Georeference']

=== Complexes ===

,Complex ID,Is Complex,Number Of Stations In Complex,Stop Name,Display Name,Constituent Station Names,Station IDs,GTFS Stop IDs,Borough,CBD,Daytime Routes,Structure Type,Latitude,Longitude,ADA,ADA Notes
0,398,False,1,77 St,77 St (6),77 St,398,627,M,False,6,Subway,40.773620,-73.959874,0,NaN
1,399,False,1,68 St-Hunter College,68 St-Hunter College (6),68 St-Hunter College,399,628,M,False,6,Subway,40.768141,-73.963870,1,NaN
2,403,False,1,33 St,33 St (6),33 St,403,632,M,True,6,Subway,40.746081,-73.982076,0,NaN
3,404,False,1,28 St,28 St (6),28 St,404,633,M,True,6,Subway,40.743070,-73.984264,2,Downtown only
4,405,False,1,23 St-Baruch College,23 St-Baruch College (6),23 St-Baruch College,405,634,M,True,6,Subway,40.739864,-73.986599,1,NaN

['Complex ID', 'Is Complex', 'Number Of Stations In Complex', 'Stop Name', 'Display Name', 'Constituent Station Names', 'Station IDs', 'GTFS Stop IDs', 'Borough', 'CBD', 'Daytime Routes', 'Structure Type', 'Latitude', 'Longitude', 'ADA', 'ADA Notes']

In [3]:
# Stations that represent complexes (multiple connected stations)

complex_stations = complexes[complexes["Is Complex"] == True].copy()

print(f"Number of complexes: {len(complex_stations)}")

display(complex_stations.head())

Number of complexes: 32

,Complex ID,Is Complex,Number Of Stations In Complex,Stop Name,Display Name,Constituent Station Names,Station IDs,GTFS Stop IDs,Borough,CBD,Daytime Routes,Structure Type,Latitude,Longitude,ADA,ADA Notes
80,601,True,3,14 St/6 Av,"14 St/6 Av (1,2,3,L,F,M)",14 St; 6 Av,116; 229; 322,132; D19; L02,M,True,1 2 3 L F M,Subway,40.737796,-73.997732,1,NaN
81,602,True,3,14 St-Union Sq,"14 St-Union Sq (4,5,6,L,N,Q,R,W)",14 St-Union Sq,15; 117; 406,635; L03; R20,M,True,4 5 6 L N Q R W,Subway,40.735066,-73.990416,2,N Q R W accessible; L accessible; 4 5 6 not ac...
82,603,True,2,149 St-Grand Concourse,"149 St-Grand Concourse (2,4,5)",149 St-Grand Concourse,390; 435,222; 415,Bx,False,2 4 5,Subway,40.818393,-73.927035,0,NaN
83,604,True,2,161 St-Yankee Stadium,"161 St-Yankee Stadium (4,B,D)",161 St-Yankee Stadium,219; 389,414; D11,Bx,False,4 B D,Elevated; Subway,40.827950,-73.925741,1,NaN
84,605,True,2,168 St-Washington Hts,"168 St-Washington Hts (1,A,C)",168 St; 168 St-Washington Hts,148; 302,112; A09,M,False,1 A C,Subway,40.840637,-73.939847,2,A C accessible; 1 not accessible

In [4]:
display(
    complex_stations[
        [
            "Complex ID",
            "Display Name",
            "Constituent Station Names",
            "Station IDs",
            "GTFS Stop IDs",
            "Daytime Routes"
        ]
    ].reset_index(drop=True)
)

,Complex ID,Display Name,Constituent Station Names,Station IDs,GTFS Stop IDs,Daytime Routes
0,601,"14 St/6 Av (1,2,3,L,F,M)",14 St; 6 Av,116; 229; 322,132; D19; L02,1 2 3 L F M
1,602,"14 St-Union Sq (4,5,6,L,N,Q,R,W)",14 St-Union Sq,15; 117; 406,635; L03; R20,4 5 6 L N Q R W
2,603,"149 St-Grand Concourse (2,4,5)",149 St-Grand Concourse,390; 435,222; 415,2 4 5
3,604,"161 St-Yankee Stadium (4,B,D)",161 St-Yankee Stadium,219; 389,414; D11,4 B D
4,605,"168 St-Washington Hts (1,A,C)",168 St; 168 St-Washington Hts,148; 302,112; A09,1 A C
5,606,"Court Sq-23 St (7,E,F,G)",Court Sq; Court Sq-23 St,274; 281; 462,719; F09; G22,7 E F G
6,607,"34 St-Herald Sq (B,D,F,M,N,Q,R,W)",34 St-Herald Sq,12; 227,D17; R17,B D F M N Q R W
7,608,"4 Av-9 St (F,G,R)",4 Av-9 St,29; 239,F23; R33,F G R
8,609,"42 St-Bryant Pk/5 Av (7,B,D,F,M)",42 St-Bryant Pk; 5 Av,226; 466,724; D16,7 B D F M
9,610,"Grand Central-42 St (4,5,6,7,S)",Grand Central-42 St,402; 465; 469,631; 723; 901,4 5 6 7 S
10,611,"Times Sq-42 St/Port Authority Bus Terminal (1,...",42 St-Port Authority Bus Terminal; Times Sq-42 St,11; 163; 317; 467; 468,127; 725; 902; A27; R16,1 2 3 7 A C E N Q R W S
11,612,"Lexington Av/51-53 Sts (6,E,F)",51 St; Lexington Av/53 St,275; 401,630; F11,6 E F
12,613,"Lexington Av/59 St (4,5,6,N,R,W)",59 St; Lexington Av/59 St,7; 400,629; R11,4 5 6 N R W
13,614,"59 St-Columbus Circle (1,A,C,B,D)",59 St-Columbus Circle,161; 315,125; A24,1 A C B D
14,615,"62 St/New Utrecht Av (D,N)",62 St; New Utrecht Av,63; 73,B16; N04,D N
15,616,"Jackson Hts-Roosevelt Av/74 St-Broadway (7,E,F...",74 St-Broadway; Jackson Hts-Roosevelt Av,267; 454,710; G14,7 E F M R
16,617,"Atlantic Av-Barclays Ctr (2,3,4,5,B,D,N,Q,R)",Atlantic Av-Barclays Ctr,27; 40; 338,235; D24; R31,2 3 4 5 B D N Q R
17,618,"14 St/8 Av (A,C,E,L)",14 St; 8 Av,115; 166,A31; L01,A C E L
18,619,"Broadway-Lafayette St/Bleecker St (6,B,D,F,M)",Bleecker St; Broadway-Lafayette St,230; 408,637; D21,6 B D F M
19,620,"Borough Hall/Court St (2,3,4,5,R)",Borough Hall; Court St,24; 335; 415,232; 423; R28,2 3 4 5 R
20,621,"Broadway Junction (A,C,J,Z,L)",Broadway Junction,92; 132; 184,A51; J27; L22,A C J Z L
21,622,"Brooklyn Bridge-City Hall/Chambers St (4,5,6,J,Z)",Brooklyn Bridge-City Hall; Chambers St,105; 411,640; M21,4 5 6 J Z
22,623,"Canal St (6,J,Z,N,Q,R,W)",Canal St,18; 19; 104; 410,639; M20; Q01; R23,6 J Z N Q R W
23,624,"Chambers St/WTC/Park Place/Cortlandt St (2,3,A...",Chambers St; Cortlandt St; Park Place; World T...,21; 170; 171; 331,228; A36; E01; R25,2 3 A C E R W
24,625,"Delancey St-Essex St (F,M,J,Z)",Delancey St-Essex St,102; 233,F15; M18,F M J Z
25,626,Franklin Av-Medgar Evers College/Botanic Garde...,Botanic Garden; Franklin Av-Medgar Evers College,142; 342,239; S04,2 3 4 5 S
26,627,"Franklin Av (C,S)",Franklin Av,139; 178,A45; S01,C S
27,628,"Fulton St (2,3,4,5,A,C,J,Z)",Fulton St,106; 172; 332; 412,229; 418; A38; M22,2 3 4 5 A C J Z
28,629,"Metropolitan Av/Lorimer St (G,L)",Lorimer St; Metropolitan Av,121; 285,G29; L10,G L
29,630,"Myrtle-Wyckoff Avs (M,L)",Myrtle-Wyckoff Avs,112; 128,L17; M08,M L
30,635,"Whitehall St-South Ferry (1,R,W)",South Ferry; Whitehall St-South Ferry,23; 330,142; R27,1 R W
31,636,"Jay St-MetroTech (A,C,F,R)",Jay St-MetroTech,25; 174,A41; R29,A C F R

In [6]:
shapes = pd.read_csv('../raw/shapes.txt')
routes = pd.read_csv('../raw/routes.txt')
trips = pd.read_csv('../raw/trips.txt')
stop_times = pd.read_csv('../raw/stop_times.txt')

print("=== Shapes ===")
display(shapes.head())
print(shapes.columns.tolist())

print("=== Routes ===")
display(routes.head())
print(routes.columns.tolist())

print("=== Trips ===")
display(trips.head())
print(trips.columns.tolist())

print("=== Stop Times ===")
display(stop_times.head())
print(stop_times.columns.tolist())

=== Shapes ===

  shape_id  shape_pt_sequence  shape_pt_lat  shape_pt_lon
0  1..N03R                  0     40.702068    -74.013664
1  1..N03R                  1     40.703199    -74.014792
2  1..N03R                  2     40.703226    -74.014820
3  1..N03R                  3     40.703253    -74.014846
4  1..N03R                  4     40.703280    -74.014870

['shape_id', 'shape_pt_sequence', 'shape_pt_lat', 'shape_pt_lon']
=== Routes ===

,route_id,agency_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_text_color,route_sort_order
0,A,MTA NYCT,A,8 Avenue Express,"Trains operate between Inwood-207 St, Manhatta...",1,https://www.mta.info/schedules/subway/a-train,0062CF,FFFFFF,1
1,C,MTA NYCT,C,8 Avenue Local,"Trains operate between 168 St, Manhattan, and ...",1,https://www.mta.info/schedules/subway/c-train,0062CF,FFFFFF,2
2,E,MTA NYCT,E,8 Avenue Local,Trains operate between Jamaica Center-Parsons/...,1,https://www.mta.info/schedules/subway/e-train,0062CF,FFFFFF,3
3,B,MTA NYCT,B,6 Avenue Express,"Trains operate, weekdays only, between 145 St,...",1,https://www.mta.info/schedules/subway/b-train,EB6800,FFFFFF,4
4,D,MTA NYCT,D,6 Avenue Express,"Trains operate, at all times, from Norwood-205...",1,https://www.mta.info/schedules/subway/d-train,EB6800,FFFFFF,5

['route_id', 'agency_id', 'route_short_name', 'route_long_name', 'route_desc', 'route_type', 'route_url', 'route_color', 'route_text_color', 'route_sort_order']
=== Trips ===

,route_id,trip_id,service_id,trip_headsign,direction_id,shape_id
0,1,ASP26GEN-1038-Sunday-00_000600_1..S03R,Sunday,South Ferry,1,1..S03R
1,1,ASP26GEN-1038-Sunday-00_002600_1..S03R,Sunday,South Ferry,1,1..S03R
2,1,ASP26GEN-1038-Sunday-00_004600_1..S03R,Sunday,South Ferry,1,1..S03R
3,1,ASP26GEN-1038-Sunday-00_006600_1..S03R,Sunday,South Ferry,1,1..S03R
4,1,ASP26GEN-1038-Sunday-00_007200_1..N03R,Sunday,Van Cortlandt Park-242 St,0,1..N03R

['route_id', 'trip_id', 'service_id', 'trip_headsign', 'direction_id', 'shape_id']
=== Stop Times ===

,trip_id,stop_id,arrival_time,departure_time,stop_sequence
0,ASP26GEN-1038-Sunday-00_000600_1..S03R,101S,00:06:00,00:06:00,1
1,ASP26GEN-1038-Sunday-00_000600_1..S03R,103S,00:07:30,00:07:30,2
2,ASP26GEN-1038-Sunday-00_000600_1..S03R,104S,00:09:00,00:09:00,3
3,ASP26GEN-1038-Sunday-00_000600_1..S03R,106S,00:10:30,00:10:30,4
4,ASP26GEN-1038-Sunday-00_000600_1..S03R,107S,00:12:00,00:12:00,5

['trip_id', 'stop_id', 'arrival_time', 'departure_time', 'stop_sequence']